function bands = eeg_get_band_ranges()
% EEG_GET_BAND_RANGES  Return standard EEG band definitions.

bands = struct( ...
    'delta',[0.5 4], ...
    'theta',[4 8], ...
    'alpha',[8 13], ...
    'beta', [13 30], ...
    'gamma',[30 45] );
end
